LOGO = "https://raw.githubusercontent.com/EniDev911/assets/main/galery/png/logos/"
MEMES = "https://raw.githubusercontent.com/EniDev911/assets/main/galery/png/memes/"
codepen = "https://img.icons8.com/external-tal-revivo-shadow-tal-revivo/96/000000/external-multi-platform-online-code-editor-and-open-source-learning-service-logo-shadow-tal-revivo.png"
github = "https://img.icons8.com/fluency/96/000000/github.png"
javascript = "https://img.icons8.com/fluency/96/000000/javascript.png"